using ASMarr;
using Microsoft.Data.Sqlite;

var root=Path.Combine(Path.GetTempPath(),"asmarr-store-tests-"+Guid.NewGuid().ToString("N"));
Directory.CreateDirectory(root);
Environment.SetEnvironmentVariable("ASMARR_STATE",Path.Combine(root,"state"));
Environment.SetEnvironmentVariable("ASMARR_CONFIG",Path.Combine(root,"config"));
var store=new Store();store.Initialize();store.Initialize();
int assertions=0;
void Assert(bool condition,string name){if(!condition)throw new InvalidOperationException(name);assertions++;Console.WriteLine("PASS "+name);}
Assert(store.Query("PRAGMA integrity_check")[0].Values.First()!.ToString()=="ok","migrations retain database integrity");
Assert(store.Query("PRAGMA journal_mode")[0].Values.First()!.ToString()=="wal","database uses WAL");
Assert(store.Query("SELECT * FROM schema_migrations").Count==2,"repeat migration is idempotent");
Assert(store.Query("SELECT * FROM tasks").Count==9,"repeat migration does not duplicate tasks");
Assert(store.Query("SELECT * FROM video_quality_profiles").Count==6,"built-in video profiles are seeded once");
Assert(store.Query("SELECT monitor_video FROM creators").Count==0,"migration does not invent creators or enable video");
Assert(store.Setting("mode")=="shadow","first boot gates production writes");
var leases=await Task.WhenAll(Enumerable.Range(0,10).Select(i=>Task.Run(()=>store.TryAcquireLease("test-provider",i.ToString(),TimeSpan.FromMinutes(1)))));
Assert(leases.Count(x=>x)==1,"concurrent tasks have exactly one lease holder");
string owner=store.Query("SELECT owner FROM task_locks WHERE name='test-provider'")[0]["owner"]!.ToString()!;
Assert(!store.RenewLease("test-provider","wrong-owner",TimeSpan.FromMinutes(1)),"another owner cannot renew lease");
store.ReleaseLease("test-provider","wrong-owner");
Assert(!store.TryAcquireLease("test-provider","next",TimeSpan.FromMinutes(1)),"another owner cannot release lease");
Assert(store.RenewLease("test-provider",owner,TimeSpan.FromMinutes(1)),"lease holder renews active execution");
store.Execute("UPDATE task_locks SET expires=$expired WHERE name='test-provider'",("expired",DateTimeOffset.UtcNow.AddMinutes(-1).ToString("O")));
Assert(store.TryAcquireLease("test-provider","replacement",TimeSpan.FromMinutes(1)),"expired leases recover after interruption");
store.ReleaseLease("test-provider",owner);
Assert(store.Query("SELECT owner FROM task_locks WHERE name='test-provider'")[0]["owner"]!.ToString()=="replacement","former owner cannot release replacement lease");
var id=store.Enqueue("health",new {test=true});
var reopened=new Store();
Assert(reopened.Query("SELECT state FROM commands WHERE id=$id",("id",id))[0]["state"]!.ToString()=="queued","commands persist across connection lifetime");
string backup=store.Backup();
using(var db=new SqliteConnection("Data Source="+backup)){db.Open();using var c=db.CreateCommand();c.CommandText="SELECT count(*) FROM commands";Assert(Convert.ToInt32(c.ExecuteScalar())==1,"SQLite online backup retains durable commands");}
Console.WriteLine($"{assertions} store integration assertions passed");
store.Execute("INSERT INTO profiles VALUES(1,'Default','{}');INSERT INTO profiles VALUES(2,'Sleep','{}')");
store.Execute("INSERT INTO creators(id,name,path,tags) VALUES(1,'First','/fixture/first','[\"Existing\"]'),(2,'Second','/fixture/second','[]')");
Assert(CreatorBatch.Apply(store,new MassEdit([1,2],ProfileId:2,AddTags:["Sleep","sleep"])) is null,"mass edit applies valid profile and deduplicated tags");
Assert(store.Query("SELECT * FROM creators WHERE profile_id=2").Count==2,"mass profile edit persists for every selected creator");
Assert(store.Query("SELECT tags FROM creators WHERE id=1")[0]["tags"]!.ToString()=="[\"Existing\",\"Sleep\"]","additive tags preserve existing labels");
Assert(CreatorBatch.Apply(store,new MassEdit([1,999],Monitored:false)) is not null,"missing creator rejects the whole batch");
Assert(Convert.ToInt32(store.Query("SELECT monitored FROM creators WHERE id=1")[0]["monitored"])==1,"failed batch rolls back earlier creator changes");
Assert(CreatorBatch.Apply(store,new MassEdit([1],ProfileId:999)) is not null,"unknown profile is rejected without changing creator");
Assert(CreatorBatch.Apply(store,new MassEdit([1],Tags:[])) is null,"explicit empty replacement can clear tags");
Assert(store.Query("SELECT tags FROM creators WHERE id=1")[0]["tags"]!.ToString()=="[]","explicit tag replacement is persisted");
Assert(Convert.ToInt32(store.Query("SELECT monitor_video FROM creators WHERE id=1")[0]["monitor_video"])==0,"audio batch editing never opts creators into videos");
Console.WriteLine($"{assertions} store integration assertions passed including atomic batch edits");
SqliteConnection.ClearAllPools();Directory.Delete(root,true);
