using ASMarr;
using Microsoft.Data.Sqlite;

var root=Path.Combine(Path.GetTempPath(),"asmarr-store-tests-"+Guid.NewGuid().ToString("N"));
Directory.CreateDirectory(root);
Environment.SetEnvironmentVariable("ASMARR_STATE",Path.Combine(root,"state"));
Environment.SetEnvironmentVariable("ASMARR_CONFIG",Path.Combine(root,"config"));
var store=new Store();store.Initialize();store.Initialize();
int assertions=0;
void Assert(bool condition,string name){if(!condition)throw new InvalidOperationException(name);assertions++;Console.WriteLine("PASS "+name);}
Assert(store.Query("PRAGMA integrity_check")[0].Values.First()!.ToString()=="ok","migrations retain database integrity");
Assert(store.Query("PRAGMA journal_mode")[0].Values.First()!.ToString()=="wal","database uses WAL");
Assert(store.Query("SELECT * FROM schema_migrations").Count==2,"repeat migration is idempotent");
Assert(store.Query("SELECT * FROM tasks").Count==9,"repeat migration does not duplicate tasks");
Assert(store.Query("SELECT * FROM video_quality_profiles").Count==6,"built-in video profiles are seeded once");
Assert(store.Query("SELECT monitor_video FROM creators").Count==0,"migration does not invent creators or enable video");
Assert(store.Setting("mode")=="shadow","first boot gates production writes");
var deployedAt=new DateTimeOffset(2026,10,8,0,0,0,TimeSpan.Zero);
var sourceCommit=new string('a',40);var artifactHash=new string('b',64);
File.WriteAllText(Path.Combine(store.Root,"deployed-release-runtime.json"),System.Text.Json.JsonSerializer.Serialize(new {sourceCommit,artifactSha256=artifactHash,deployedAt}));
var parity=new Dictionary<string,object?> {
    ["sourceCommit"]=sourceCommit,["artifactSha256"]=artifactHash,["legacyImplementationSha256"]=new string('c',64),
    ["discoveryParity"]=true,["eligibilityAndSourceParity"]=true,["checkpointCalculationParity"]=true,
    ["productionCheckpointsUnchanged"]=true,["applicationCheckpointsUnchanged"]=true,["mediaUnchanged"]=true,
    ["playlistPreviewHealthy"]=true,["playlistCalculationParity"]=true
};
store.Execute("INSERT INTO shadow_cycles(started,finished,result,clean,comparison) VALUES($started,$started,'{}',1,$comparison)",("started","2026-10-08T01:00:00Z"),("comparison",System.Text.Json.JsonSerializer.Serialize(parity)));
store.Execute("INSERT INTO shadow_cycles(started,finished,result,clean,comparison) VALUES($started,$started,'{}',1,$comparison)",("started","2026-10-07T01:00:00Z"),("comparison",System.Text.Json.JsonSerializer.Serialize(parity)));
parity["sourceCommit"]=new string('d',40);
store.Execute("INSERT INTO shadow_cycles(started,finished,result,clean,comparison) VALUES($started,$started,'{}',1,$comparison)",("started","2026-10-09T01:00:00Z"),("comparison",System.Text.Json.JsonSerializer.Serialize(parity)));
store.Execute("INSERT INTO shadow_cycles(started,finished,result,clean,comparison) VALUES($started,$started,'{}',1,'not-json')",("started","2026-10-10T01:00:00Z"));
Assert(ShadowQualification.Count(store)==1,"status counts only current-release post-deployment shadow evidence");
var leases=await Task.WhenAll(Enumerable.Range(0,10).Select(i=>Task.Run(()=>store.TryAcquireLease("test-provider",i.ToString(),TimeSpan.FromMinutes(1)))));
Assert(leases.Count(x=>x)==1,"concurrent tasks have exactly one lease holder");
string owner=store.Query("SELECT owner FROM task_locks WHERE name='test-provider'")[0]["owner"]!.ToString()!;
Assert(!store.RenewLease("test-provider","wrong-owner",TimeSpan.FromMinutes(1)),"another owner cannot renew lease");
store.ReleaseLease("test-provider","wrong-owner");
Assert(!store.TryAcquireLease("test-provider","next",TimeSpan.FromMinutes(1)),"another owner cannot release lease");
Assert(store.RenewLease("test-provider",owner,TimeSpan.FromMinutes(1)),"lease holder renews active execution");
store.Execute("UPDATE task_locks SET expires=$expired WHERE name='test-provider'",("expired",DateTimeOffset.UtcNow.AddMinutes(-1).ToString("O")));
Assert(store.TryAcquireLease("test-provider","replacement",TimeSpan.FromMinutes(1)),"expired leases recover after interruption");
store.ReleaseLease("test-provider",owner);
Assert(store.Query("SELECT owner FROM task_locks WHERE name='test-provider'")[0]["owner"]!.ToString()=="replacement","former owner cannot release replacement lease");
var id=store.Enqueue("health",new {test=true});
var reopened=new Store();
Assert(reopened.Query("SELECT state FROM commands WHERE id=$id",("id",id))[0]["state"]!.ToString()=="queued","commands persist across connection lifetime");
string backup=store.Backup();
using(var db=new SqliteConnection("Data Source="+backup)){db.Open();using var c=db.CreateCommand();c.CommandText="SELECT count(*) FROM commands";Assert(Convert.ToInt32(c.ExecuteScalar())==1,"SQLite online backup retains durable commands");}
Console.WriteLine($"{assertions} store integration assertions passed");
store.Execute("INSERT INTO profiles VALUES(1,'Default','{}');INSERT INTO profiles VALUES(2,'Sleep','{}')");
store.Execute("INSERT INTO creators(id,name,path,tags) VALUES(1,'First','/fixture/first','[\"Existing\"]'),(2,'Second','/fixture/second','[]')");
Assert(CreatorBatch.Apply(store,new MassEdit([1,2],ProfileId:2,AddTags:["Sleep","sleep"])) is null,"mass edit applies valid profile and deduplicated tags");
Assert(store.Query("SELECT * FROM creators WHERE profile_id=2").Count==2,"mass profile edit persists for every selected creator");
Assert(store.Query("SELECT tags FROM creators WHERE id=1")[0]["tags"]!.ToString()=="[\"Existing\",\"Sleep\"]","additive tags preserve existing labels");
Assert(CreatorBatch.Apply(store,new MassEdit([1,999],Monitored:false)) is not null,"missing creator rejects the whole batch");
Assert(Convert.ToInt32(store.Query("SELECT monitored FROM creators WHERE id=1")[0]["monitored"])==1,"failed batch rolls back earlier creator changes");
Assert(CreatorBatch.Apply(store,new MassEdit([1],ProfileId:999)) is not null,"unknown profile is rejected without changing creator");
Assert(CreatorBatch.Apply(store,new MassEdit([1],Tags:[])) is null,"explicit empty replacement can clear tags");
Assert(store.Query("SELECT tags FROM creators WHERE id=1")[0]["tags"]!.ToString()=="[]","explicit tag replacement is persisted");
Assert(Convert.ToInt32(store.Query("SELECT monitor_video FROM creators WHERE id=1")[0]["monitor_video"])==0,"audio batch editing never opts creators into videos");
var registration=CreatorRegistration.Create(store,new NewCreator("New Creator",2,Aliases:["Alias"],Tags:["Sleep"],Identities:[new("soundgasm","Handle"),new("reddit","Handle")]));
Assert(registration.Id is not null&&registration.Error is null,"creator onboarding persists valid identities atomically");
Assert(store.Query("SELECT * FROM identities WHERE creator_id=$id",("id",registration.Id)).Count==2,"one creator can link multiple source identities");
var created=store.Query("SELECT * FROM creators WHERE id=$id",("id",registration.Id))[0];
Assert(Convert.ToInt32(created["monitor_video"])==0,"creator onboarding never opts into video");
Assert(!Directory.Exists(created["path"]!.ToString()),"creator onboarding does not write media directories");
var visual=CreatorRegistration.Create(store,new NewCreator("Visual Creator",2,MonitorVideo:true,VideoQualityProfileId:4));
var visualRow=store.Query("SELECT monitor_video,video_quality_profile_id FROM creators WHERE id=$id",("id",visual.Id))[0];
Assert(Convert.ToInt32(visualRow["monitor_video"])==1&&Convert.ToInt32(visualRow["video_quality_profile_id"])==4,"creator onboarding persists explicit video monitoring and profile selection");
Assert(CreatorRegistration.Create(store,new NewCreator("Invalid video profile",2,MonitorVideo:true,VideoQualityProfileId:999)).Error is not null,"creator onboarding validates video quality profile");
Assert(CreatorRegistration.Create(store,new NewCreator("new creator",2)).Error is not null,"case-insensitive duplicate creator is rejected");
Assert(CreatorRegistration.Create(store,new NewCreator("../Escape",2)).Error is not null,"creator path traversal is rejected");
Assert(CreatorRegistration.Create(store,new NewCreator("Invalid profile",999)).Error is not null,"onboarding validates acquisition profile");
Assert(CreatorRegistration.Create(store,new NewCreator("Conflicting Creator",2,Identities:[new("reddit","handle")])).Error is not null,"an identity cannot be owned by another creator");
Assert(store.Query("SELECT * FROM creators").Count==4,"rejected onboarding leaves no partial creators");
Assert(CreatorRegistration.Link(store,999,new("reddit","Unowned")).Error is not null,"linking validates creator ownership");
Assert(CreatorRegistration.Link(store,1,new("soundgasm","handle")).Error is not null,"linking cannot claim another creator identity");
Assert(CreatorRegistration.Link(store,1,new("soundgasm",null!)).Error is not null,"null source handles are rejected safely");
Assert(CreatorRegistration.Link(store,1,new("soundgasm","SecondHandle")).Id is not null,"existing creators can link additional source identities");
store.Execute("UPDATE creators SET monitor_video=1 WHERE id=1");
store.Execute("INSERT INTO backfill_jobs(id,creator_id,media_kind,state,cursor,started,updated) VALUES('resume-video',1,'Video','running','{\"phase\":\"known\",\"index\":2}',$now,$now)",("now",DateTimeOffset.UtcNow.ToString("O")));
store.InterruptRunningVideoBackfills();
Assert(store.Query("SELECT state FROM backfill_jobs WHERE id='resume-video'")[0]["state"]!.ToString()=="interrupted","service restart checkpoints an executing video history scan");
Assert(store.EnqueueResumableVideoBackfills(TimeSpan.FromMinutes(5))==1,"interrupted video history scan is requeued automatically");
Assert(store.Query("SELECT * FROM commands WHERE name='video-backfill' AND state='queued' AND CAST(json_extract(arguments,'$.creatorId') AS INTEGER)=1").Count==1,"resumed video history command retains creator scope");
Assert(store.EnqueueResumableVideoBackfills(TimeSpan.FromMinutes(5))==0,"recovery never duplicates an active video history command");
store.Execute("UPDATE commands SET state='failed' WHERE name='video-backfill';UPDATE backfill_jobs SET state='failed',updated=$old WHERE id='resume-video'",("old",DateTimeOffset.UtcNow.AddMinutes(-10).ToString("O")));
Assert(store.EnqueueResumableVideoBackfills(TimeSpan.FromMinutes(5))==1,"transient video history failures retry after the bounded delay");
store.Execute("UPDATE creators SET monitor_video=0 WHERE id=1;UPDATE commands SET state='failed' WHERE name='video-backfill';UPDATE backfill_jobs SET state='interrupted' WHERE id='resume-video'");
Assert(store.EnqueueResumableVideoBackfills(TimeSpan.Zero)==0,"disabled video monitoring never resumes a cancelled history scan");
store.Execute("INSERT INTO assets(key,url,targets,source,creator,title,state) VALUES('legacy-audio','fixture:legacy','[]','soundgasm','First','Legacy audio','complete'),('new-audio','fixture:new','[]','soundgasm','First','New audio','complete')");
store.Execute("UPDATE media_assets SET state='imported' WHERE recording_key='new-audio' AND media_kind='Audio'");
store.Execute("INSERT INTO media_assets(recording_key,media_kind,state) VALUES('legacy-audio','Video','imported')");
var totals=CreatorLibrary.Read(store).Single(row=>row["name"]!.ToString()=="First");
Assert(Convert.ToInt32(totals["audio_completed"])==2,"creator totals include legacy complete and new imported audio");
Assert(Convert.ToInt32(totals["video_completed"])==1,"video totals remain independent of audio compatibility states");
Assert(store.Query("SELECT state FROM media_assets WHERE recording_key='legacy-audio' AND media_kind='Audio'")[0]["state"]!.ToString()=="complete","creator totals preserve migrated audio state without rewriting records");
Console.WriteLine($"{assertions} store integration assertions passed");
SqliteConnection.ClearAllPools();Directory.Delete(root,true);
